# CHANGEME: Set these variable to your liking
title: FridgeTroll
description: ESPHome-based smart controller for SECOP compressor-driven refrigerators, providing advanced temperature management, stall detection, and telemetry.
theme: jekyll-theme-slate
